### ISSUE TITLE
Get example dataset from a network participant

### ISSUE THREAD

**Issue by lzachmann** [lzachmann/sevilleta-workshop-tester#15]
Obtain an example of a dataset from one of the I&M networks ahead of the workshop, even if it's somewhat dirty/incomplete. Would be good to see what a representative dataset would look like.

**Comment by schererrd** [comment]
We have an example dataset from Erin Borgman. Erin is part of the Rocky Mountain Network and is an ecologist/field coordinator.

**Comment by schererrd** [comment]
I just sent an e-mail to Erin and requested information on the projection. More to come...

**Comment by lzachmann** [comment]
Thanks Rick, I suspect it's [zone 13N](http://spatialreference.org/ref/epsg/nad83-utm-zone-13n/).

**Comment by schererrd** [comment]
I overlaid the area covered by the Rocky Mountain Network on a UTM zones map, and you are probably right (unless their samples come from the northern part of that network).

**Comment by lzachmann** [comment]
Indeed. 

![screen shot 2017-02-09 at 11 36 57 am](https://cloud.githubusercontent.com/assets/7574887/22799867/301a2f3e-eebc-11e6-8079-50d5e190afc8.png)

**Comment by schererrd** [comment]
Just heard back form Erin, and the zone is 13N.
