### ISSUE TITLE
Navbar formatting to include CSP logo

### ISSUE THREAD

**Issue by lzachmann** [lzachmann/sevilleta-workshop-tester#16]
Either hard-code or build into e.g., [rmdy](https://github.com/csp-inc/rmdy), but perhaps insert company logo (if not company name plus logo, depending on device size).

**Comment by blindjesse** [comment]
How are you building the website?

**Comment by lzachmann** [comment]
Using an [R Markdown Website](http://rmarkdown.rstudio.com/rmarkdown_websites.html) hosted from the /docs page of the repo.

**Comment by blindjesse** [comment]
So 'rmarkdown::render_site'?

**Comment by lzachmann** [comment]
Yes, sorry about that. I believe if your working directory is `PROJ_ROOT/docs` you can run `rmarkdown::render_site()` and it will knit every `.Rmd` sequentially. FWIW, only the master branch can be used to build the website as a GitHub Page. Also, you might comment out the leaflet map in the 'about.Rmd' file for now. I need to put that elsewhere and use an iframe or something. Tends to bloat the size of that page.

**Comment by blindjesse** [comment]
Ok I added the logo to the navbar and the the copyright to the bottom with 1e483bf. Haven't rebuilt `use_cases.html` yet but I wanted to commit before too many things changed.

**Comment by lzachmann** [comment]
Tested with 71d13b0. Looks great! Closing....
