### ISSUE TITLE
Microsoft RDC connection

### ISSUE THREAD

**Issue by lzachmann** [lzachmann/sevilleta-workshop-tester#19]
Determine whether Microsoft RDC might be a viable alternative to x2goclient.

**Comment by blindjesse** [comment]
Ok, some things here:

1. I couldn't get rdp working easily with the existing vm. It could take some time...something to do with centos 7 or the ds vm, I don't know. I provisioned another VM to see if that would be easier and that IS working. BUT,
2. Doesn't look like Rstudio will work through RDP at all. BUT,
3. If we stay with x2goclient I am a little concerned about performance, see for instance [this](http://unix.stackexchange.com/questions/1960/differences-between-vnc-and-ssh-x) (I think x2go just tunnels using ssh). We may need to do some testing with multiple users hitting the vm at the same time, probably after upgrading the cores /etc.

**Comment by lzachmann** [comment]
Right, good idea. I could do some testing this afternoon potentially. Not
commited to Microsoft RDC at all — just figured it might be somewhat easier
or more familiar than X2Go.

--
Luke Zachmann
Senior Scientist
Conservation Science Partners
11050 Pioneer Trail, Suite 202
Truckee, CA 96161
Tel 530.214.8905 <//530.214.8905>; Fax 530.214.8907 <//530.214.8907>

On February 10, 2017 at 10:18:39 AM, Jesse Anderson (
notifications@github.com) wrote:

Ok, some things here:

   1. I couldn't get rdp working easily with the existing vm. It could take
   some time...something to do with centos 7 or the ds vm, I don't know. I
   provisioned another VM to see if that would be easier and that IS working.
   BUT,
   2. Doesn't look like Rstudio will work through RDP at all. BUT,
   3. If we stay with x2goclient I am a little concerned about performance,
   see for instance this
   <http://unix.stackexchange.com/questions/1960/differences-between-vnc-and-ssh-x>
   (I think x2go just tunnels using ssh). We may need to do some testing with
   multiple users hitting the vm at the same time, probably after upgrading
   the cores /etc.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lzachmann/sevilleta-workshop-tester/issues/19#issuecomment-279022881>,
or mute the thread

**Comment by blindjesse** [comment]
Ok, I will put this issue in lower priority.

**Comment by blindjesse** [comment]
I think due to Rstudio being a no-go that we should forget about this

**Comment by lzachmann** [comment]
Agreed.

--
Luke Zachmann
Senior Scientist
Conservation Science Partners
11050 Pioneer Trail, Suite 202
Truckee, CA 96161
Tel 530.214.8905 <//530.214.8905>; Fax 530.214.8907 <//530.214.8907>

On February 10, 2017 at 11:17:51 AM, Jesse Anderson (
notifications@github.com) wrote:

I think due to Rstudio being a no-go that we should forget about this

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lzachmann/sevilleta-workshop-tester/issues/19#issuecomment-279039164>,
or mute the thread
