### ISSUE TITLE
Rstudio and conda env

### ISSUE THREAD

**Issue by blindjesse** [lzachmann/sevilleta-workshop-tester#20]
Rstudio in GUI config unable to use conda env libraries (and uses non-conda R, but that is lesser issue). 

One option would seem to be loading conda env then starting rstudio from that terminal but rstudio seems to hang this way. 

Another option would be to load conda env on login (even more than that though - environment would need to be loaded when rstudio starts in gui). 

Other option may be to load all the needed libraries into "root" conda env and prepend /anaconda/bin to PATH (for conda R, if needed), or at least get the root conda env into .libPaths().

**Comment by lzachmann** [comment]
Jesse, did you check out the instructions I created[here](https://lzachmann.github.io/sevilleta-workshop-tester/)? I was able to get this going -- no problems with RStudio hanging.... But perhaps I'm missing something?

**Comment by blindjesse** [comment]
Hmm, still hanging for me under userf552. Not sure it's a performance issue (checked azure db, only thing that's way up is disk read). Will take a closer look.

**Comment by blindjesse** [comment]
Ok, working after reboot. Will continue to monitor
